config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  ActiveAdmin.routes(self)
  root to: "users#show"
  devise_for :users
  resources :users, only: [:show] do
    collection do
      get "search"
    end
  end
  resources :event_entries
  resources :reviews
  resources :comments
  resources :presentations
  resources :events
  resources :room_usages, only: %i[index new]
  resources :mics
  resources :bands, only: [:index]
  resources :regular_bands, only: %i[new create show edit update]
  resources :temporal_bands, only: %i[new create show edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/mics/order/:id", to: "mics#order"
  post "/mics/order/:id/:order", to: "mics#order_update"
end

app/models/mic.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: mics
#
#  id            :bigint(8)        not null, primary key
#  date          :date             not null
#  end_time      :time
#  order         :integer
#  pa_attendance :string
#  remark        :text
#  start_time    :time
#  status        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  band_id       :bigint(8)        not null
#  period_id     :bigint(8)        not null
#  room_id       :bigint(8)
#  user_id       :bigint(8)        not null
#
# Indexes
#
#  index_mics_on_band_id    (band_id)
#  index_mics_on_period_id  (period_id)
#  index_mics_on_room_id    (room_id)
#  index_mics_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (band_id => bands.id)
#  fk_rails_...  (period_id => periods.id)
#  fk_rails_...  (room_id => rooms.id)
#  fk_rails_...  (user_id => users.id)
#

class Mic < ApplicationRecord
<<<<<<< HEAD
	#RELATION
	belongs_to :user
	belongs_to :band
	belongs_to :room, optional: true
	belongs_to :period

	#QUERY
	scope :eliminate_past, -> { where('date > ?',Date.today ) }
	scope :on_date, ->(date) { where('date = ?',date ) }
	scope :unique_dates, -> { select(:date).distinct.map(&:date).sort }

	#CLARIFY
	enum status: { unapproved: 0, approved: 1, declined: 2 } 

=======
  belongs_to :user
  belongs_to :band
  belongs_to :room, optional: true
  belongs_to :period
>>>>>>> 9444d28d7844c092fc23b71a6845a552a5facf5e
end

app/controllers/mics_controller.rb
# frozen_string_literal: true

# どんさん担当
class MicsController < ApplicationController
  # マイク練一覧画面(マイク練係確認用)
  def index
    @mics = Mic.where("date >= ?", Date.today).order(date: "ASC", period_id: "ASC", order: "ASC")
  end

  # 申請フォームは後から他のやつを使い回すので大丈夫です。
  def new; end

  def create; end

  # 自分のマイク練一覧画面
  def show
    @mics = Mic.where("date >= ?", Date.today).where(band_id: User.find(params[:id]).bands.map(&:id)).order(date: "ASC", period_id: "ASC", order: "ASC")
  end

  def edit; end

  def update; end

  def destroy; end

  # 分割順番選択画面
  def order
    @mic = Mic.find(params[:id])
  end

  def order_update
    @mic = Mic.find(params[:id])
    @mic.update_attributes(order: params[:order])
  end
end

app/helpers/mics_helper.rb
# frozen_string_literal: true

module MicsHelper
  # マイク練分割数を出力
  def split_mic_count(mic)
    Mic.select { |m| m.date == mic.date && m.period_id == mic.period_id }.count
  end

  # 該当分割マイク練でn番目に入ってるバンドが存在するか
  def mic_order_any?(mic, num)
    Mic.select { |m| m.date == mic.date && m.period_id == mic.period_id && m.order == num }.any?
  end

  # 該当分割マイク練でn番目に入ってるバンドの名前を取得
  def ordered_band_name(mic, num)
    Mic.select { |m| m.date == mic.date && m.period_id == mic.period_id && m.order == num }.first.band.name
  end

  # マイク練の状態出力
  def mic_status_string(mic)
    if mic.status == 1
      "承認済み"
    elsif mic.status == 2
      "キャンセル"
    else
      "未承認"
    end
  end

  # PA出席の状態出力
  def pa_attendance_string(mic)
    mic.pa_attendance ? "PA出席" : "PA欠席"
  end
end

app/views/mics/index.html.haml
.uk-width-2-3@m.uk-padding-small.uk-margin-auto
  .uk-text-large マイク練申請一覧
  %ul.uk-tab.uk-margin-top{'uk-tab': ''}
    %li
      %a{href:'#'} 全て
    %li
      %a{href:'#'} 未承認
    %li
      %a{href:'#'} 承認済み
  %ul.uk-switcher
    %li
      -# TABLE OF MICS (ALL)
      %table.uk-table.uk-table-divider.uk-table-small
        %thead
          %tr
            %th BAND
            %th TIME
            %th STATUS
            %th PA
            %th EDIT
        %tbody
          - if Mic.eliminate_past.none?
            %tr.uk-background-muted
              %td{colspan: 5} ※表示するデータがありません。
          - Mic.eliminate_past.unique_dates.each do |date|
            %tr.uk-background-muted
              %td{colspan: 4}= date.strftime("%Y/%m/%d") 
              %td
                %a.uk-icon-link{'uk-toggle': "target: #data#{date}; animation: uk-animation-slide-top-small", 'uk-icon': 'chevron-down'}
            - Mic.on_date(date).each do |mc|
              %tr{id: "data#{date}"}
                %td.uk-text-truncate= mc.band.name
                %td= mc.period.name
                %td
                  - case 
                    -when mc.unapproved?
                      .uk-label.uk-margin-auto.uk-label-default 未承認
                    -when mc.approved?
                      .uk-label.uk-margin-auto.uk-label-success 承認済
                    -when mc.declined?
                      .uk-label.uk-margin-auto.uk-label-danger 否認
                %td.uk-text-truncate= mc.band.pa.name
                %td
                  %a.uk-icon-link{'uk-icon': 'menu'}
        
    %li
      %table.uk-table.uk-table-divider.uk-table-small
        %thead
          %tr
            %th BAND
            %th TIME
            %th STATUS
            %th PA
            %th EDIT
        %tbody
          - if Mic.eliminate_past.unapproved.unique_dates.none?
            %tr.uk-background-muted
              %td{colspan: 5} 表示するデータがありません。
          - Mic.eliminate_past.unapproved.unique_dates.each do |date|
            %tr.uk-background-muted
              %td{colspan: 4}= date.strftime("%Y/%m/%d") 
              %td
                %a.uk-icon-link{'uk-toggle': "target: #uapdata#{date}; animation: uk-animation-slide-top-small", 'uk-icon': 'chevron-down'}
            - Mic.on_date(date).unapproved.each do |mc|
              %tr{id: "uapdata#{date}"}
                %td.uk-text-truncate= mc.band.name
                %td= mc.period.name
                %td
                  .uk-label.uk-margin-auto.uk-label-default 未承認
 
                %td.uk-text-truncate= mc.band.pa.name
                %td
                  %a.uk-icon-link{'uk-icon': 'menu'}
    %li
      %table.uk-table.uk-table-divider.uk-table-small
        %thead
          %tr
            %th BAND
            %th TIME
            %th STATUS
            %th PA
            %th EDIT
        %tbody
          - if Mic.eliminate_past.approved.unique_dates.none?
            %tr.uk-background-muted
              %td{colspan: 5} 表示するデータがありません。
              
          - Mic.eliminate_past.approved.unique_dates.each do |date|
            %tr
              %td.uk-background-muted{colspan: 4}= date.strftime("%Y/%m/%d") 
              %td
                %a.uk-icon-link{'uk-toggle': "target: #decdata#{date}; animation: uk-animation-slide-top-small", 'uk-icon': 'chevron-down'}
            - Mic.on_date(date).approved.each do |mc|
              %tr{id: "#decdata#{date}"}
                %td.uk-text-truncate= mc.band.name
                %td= mc.period.name
                %td
                  .uk-label.uk-margin-auto.uk-label-success 承認済
                %td.uk-text-truncate= mc.band.pa.name
                %td
                  %a.uk-icon-link{'uk-icon': 'menu'}




-# .uk-text-center.uk-text-large マイク練一覧画面(音響用)

-# .uk-container.uk-width-2-3@s.uk-margin-auto.uk-padding-small(uk-accordion="multiple: true")
-#   - mic_date = @mics.map(&:date).uniq
-#   - mic_date.each do |date|
-#     .day-wrap
-#       %a{href: "#", class: "uk-accordion-title"}
-#         .belt= date
-#       .uk-accordion-content.content-wrap
-#         - mic_period = @mics.where(date: date).map(&:period).uniq
-#         - mic_period.each do |period|
-#           /限表示
-#           .time-wrap
-#             = "== "+period.name+" =="

-#           /各マイク練表示
-#           - @mics.where(date: date, period: period).each do |mic|
-#             /同じ限のマイク練表示
-#             .split-wrap
-#               /マイク練順番
-#               .order-wrap.flex-center
-#                 - if mic.order
-#                   = mic.order
-#                 - else
-#                   .not-define= "未定"

-#               /部屋ボタン
-#               .room-wrap.flex-center
-#                 - if mic.room
-#                   = mic.room.name
-#                 - else
-#                   .not-define= "部屋未定" #TODO:部屋登録用モーダル作る

-#               /備考ボタン
-#               .remark-wrap.flex-center
-#                 - if mic.remark
-#                   %input{type: "button", value: "備考あり", onclick: "alert('#{mic.remark}')" }
-#                 - else
-#                   = "備考なし"

-#               /バンド名
-#               .band-wrap.flex-center
-#                 = mic.band.name

-#               /ステータス変更ボタン(削除をここでできるようにする)
-#               /.approve-wrap.mic-button.flex-center.button-edge-top-right
-#               = link_to mic_path(mic), method: 'PATCH', data: { confirm: "ステータスを変更します(未実装)" },  class: "approve-wrap mic-button button-edge-top-right flex-center" do
-#                 .flex-center= mic_status_string(mic)

-#               /PA出席ボタン
-#               = link_to  mic_path(mic), method: 'PATCH', data: { confirm: "PA出席を変更します(未実装)" }, class: "pa-wrap mic-button" do
-#                 .flex-center= pa_attendance_string(mic)
-#                 .flex-center= "PA-Name"#mic.band.pa.name#paのリレーション組んでないので動きません

-#               /連絡ボタン
-#               = link_to mic_path(mic), method: 'PATCH', data: { confirm: "バンマスへ連絡します。(未実装)"}, class: "contact-wrap mic-button button-edge-bottom-right" do
-#                 .flex-center= "バンマスへ"
-#                 .flex-center= "連絡" #TODO: クリックでメール送信画面

app/views/mics/order.html.haml
.uk-section-xsmall.uk-text-large
  .flex-center
    = @mic.date.to_s + " " + @mic.period.name
  .flex-center
    = @mic.band.name

.uk-padding-remove-vertical
  - split_mic_count(@mic).times do |i|
    .link-button-padding
      - unless mic_order_any?(@mic, i+1) #分割一番目に他のバンドがなければ
        = link_to("/order/#{@mic.id}/#{i+1}",:method => 'POST', data: { confirm: "#{i+1}番目でよろしいですか？" },class: 'link-button' ) do
          ="#{i+1}番目を希望する"
      - else
        .link-button-pressed
          = "#{i+1}番目：" + ordered_band_name(@mic, i+1)

app/views/mics/order_update.html.haml
/順番登録完了の仮画面
.flex-center.uk-section-small
  =params[:order]+"番目に登録しました。"

app/views/mics/show.html.haml
%h2 マイク練一覧(個人用)

-#表示部分は別ファイルにするかも
- mic_date = @mics.map(&:date).uniq
- mic_date.each do |date|
  = date #日付表示
  - @mics.where(date: date).each do |mic| #該当日付のマイク練表示
    = mic.period #限表示
    = mic.order if mic.order #分割あれば順番表示

    - if mic.room
      = mic.room
    - else
      = "部屋未定"

    = mic.band.name
    = mic.band.pa.name if mic.band.type == "RegularBand"
    = mic.pa_attendance if mic.band.type == "RegularBand"