config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  ActiveAdmin.routes(self)
  root to: "users#show"
  devise_for :users
  resources :users, only: [:show] do
    collection do
      get "search"
    end
  end
  resources :event_entries
  resources :reviews
  resources :comments
  resources :presentations
  resources :events
  resources :room_usages, only: %i[index new]
  resources :mics
  resources :bands, only: [:index]
  resources :regular_bands, only: %i[new create show edit update]
  resources :temporal_bands, only: %i[new create show edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/mics/order/:id", to: "mics#order"
  post "/mics/order/:id/:order", to: "mics#order_update"
end

app/models/band/regular_band.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bands
#
#  id            :bigint(8)        not null, primary key
#  description   :text
#  name          :string           not null
#  registeration :boolean          not null
#  type          :string
#  web_url       :string
#  year          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  master_id     :bigint(8)        not null
#  pa_id         :bigint(8)        not null
#
# Indexes
#
#  index_bands_on_master_id  (master_id)
#  index_bands_on_pa_id      (pa_id)
#
# Foreign Keys
#
#  fk_rails_...  (master_id => users.id)
#  fk_rails_...  (pa_id => users.id)
#

class RegularBandValidator < ActiveModel::Validator
  def validate(record)
    unless !record.type.nil? && record.type.match("RegularBand")
      record.errors[:type] << "は正規バンドでなければいけません"
    end
  end
end

class RegularBand < Band
  include ActiveModel::Validations
  belongs_to :pa, class_name: "User", foreign_key: "pa_id"
  validates :year, presence: true
  validates :description, presence: true
  validates_with RegularBandValidator
end

app/controllers/regular_bands_controller.rb
# frozen_string_literal: true

class RegularBandsController < ApplicationController
  before_action :set_regular_band, only: %i[edit update show]

  def new
    @regular_band = RegularBand.new
  end

  def create
    @regular_band = new_regular_band(regular_band_params)
    if @regular_band.save
      @regular_band_members = new_members(regular_band_params, @regular_band)
      success = @regular_band_members.map(&:save)
      if success.all?
        redirect_to root_path, notice: "バンドを作成しました"
      else
        @regular_band_members.map(&:delete)
        render :new, notice: "バンドメンバーを登録できませんでした"
      end
    else
      render :new, notice: "バンドメンバーを登録できませんでした"
    end
  end

  def show; end

  def edit; end

  def update; end

  private

  def regular_band_params
    params.require(:regular_band).permit(
      :name,
      :year,
      :description,
      :web_url,
      :master_id,
      :pa_id,
      members: %i[
        user_id
        mic_number
      ]
    )
  end

  def new_regular_band(params)
    band = RegularBand.new(
      type: "RegularBand",
      name: params[:name],
      year: params[:year],
      description: params[:description],
      web_url: params[:web_url],
      master_id: params[:master_id],
      pa_id: params[:pa_id],
      registeration: false
    )
    band
  end

  def new_members(params, band)
    band_members = []
    if params[:members].present?
      params[:members].map do |member|
        raise "error" if member[:user_id].nil?
        raise "error" if member[:mic_number].nil?

        band_member = BandMember.new(
          user_id: member[:user_id],
          band_id: band.id,
          mic_number: member[:mic_number]
        )
        band_members.push(band_member)
      end
    end
    band_members
  end

  def set_regular_band
    @regular_band = RegularBand.find(params[:id])
  end
end

app/helpers/regular_bands_helper.rb
# frozen_string_literal: true

module RegularBandsHelper
end

app/views/regular_bands/edit.html.haml
.flex-center
  = form_for @regular_band do |f|
    - if @regular_band.errors.any?
      #error_explanation
        %h2= "#{@regular_band.errors.full_messages.count}件のエラーが発生たため、バンドは編集されませんでした："
        %ul
          - @regular_band.errors.full_messages.each do |message|
            %li= message
    =f.hidden_field :type, value: "RegularBand"
    %legend.uk-legend.form-title.flex-center 正規バンド編集
    .field
      = f.label :バンド名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :結成年, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: calendar"}
        = f.text_field :year, class: "uk-input field-input"
    .field
      = f.label :バンドの説明, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: pencil"}
        = f.text_field :description, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :Webページ, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: world"}
        = f.text_field :web_url, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :バンドマスター, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-xsmall
          .uk-container
            %input{:name => "regular_band[master_id]", :type => "hidden", :value => "#{@regular_band.master.id}"}
            .band-member_year-section
              = @regular_band.master.year
              = @regular_band.master.section.name
            .band-member_name
              = @regular_band.master.name
    .field
      = f.label :PA, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#pa-search-field{placeholder: "PAの名前を入力してください", type: "text", name: "keyword"}
        #pa-search-result
      #pa-box
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-xsmall
          .uk-container
            %input{:name => "regular_band[pa_id]", :type => "hidden", :value => "#{@regular_band.pa.id}"}
            .band-member_year-section
              = @regular_band.pa.year
              = @regular_band.pa.section.name
            .band-member_name
              = @regular_band.pa.name
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
              -@regular_band.users.includes(:section).each do |user|
                %li.band-member
                  %input{:name => "regular_band[members][][user_id]", :type => "hidden", :value => "#{user.id}"}
                  .band-member_year-section
                    = user.year
                    = user.section.name
                  .band-member_name
                    = user.name
                  .band-member_mic-number
                    マイク番号
                    %select{:name => "regular_band[members][][mic_number]"}
                      %option{:value => "1"} 1番
                      %option{:value => "2"} 2番
                      %option{:value => "3"} 3番
                      %option{:value => "4"} 4番
                      %option{:value => "5"} 5番
                      %option{:value => "6"} 6番
                      %option{:value => "7"} 7番
                  %a.band-member_remove-button 消去
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"

app/views/regular_bands/new.html.haml
.flex-center
  = form_for @regular_band do |f|
    - if @regular_band.errors.any?
      #error_explanation
        %h2= "#{@regular_band.errors.full_messages.count}件のエラーが発生たため、バンドは登録されませんでした："
        %ul
          - @regular_band.errors.full_messages.each do |message|
            %li= message
    %legend.uk-legend.form-title.flex-center 正規バンド登録
    .field
      = f.label :バンド名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :結成年, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: calendar"}
        = f.text_field :year, class: "uk-input field-input"
    .field
      = f.label :バンドの説明, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: pencil"}
        = f.text_field :description, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :Webページ, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: world"}
        = f.text_field :web_url, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :バンドマスター, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
    .field
      = f.label :PA, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#pa-search-field{placeholder: "PAの名前を入力してください", type: "text", name: "keyword"}
        #pa-search-result
      #pa-box
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"

app/views/regular_bands/show.html.haml
- if user_band_member?(@regular_band, current_user)
  = link_to "編集", edit_regular_band_path, class: "show-band-edit"

.uk-margin-auto.uk-width-2-3@m.uk-padding-small{'uk-grid': ''}
  .uk-padding-small.uk-width-1-2@m
    %img.show-band-picture{"src" => "http://www.acappellazone.com/fileadmin/user_upload/ACAPPELLAZONE/TOP_ACTS/Slixs/SLIXS-hagen-wolf-3_slider.jpg"}
  .uk-padding-small.uk-width-1-2@m
    %h2= @regular_band.name
    .uk-tile.uk-tile-muted.uk-padding-small.uk-margin-top ABOUT
    .uk-text.uk-padding-small= @regular_band.description
    .uk-tile.uk-tile-muted.uk-padding-small.uk-margin-top MEMBERS
    %ul.uk-list
      -6.times do |i|
        %li= "dummy member #{i + 1}"
      -@regular_band.users.each do |us|
        %li= us.name
    .uk-tile.uk-tile-muted.uk-padding-small.uk-margin-top LEADER
    .uk-text-small.uk-padding-small
      = @regular_band.master.name
    .uk-tile.uk-tile-muted.uk-padding-small.uk-margin-top PA
    .uk-text-small.uk-padding-small
      = @regular_band.pa.name






-# %legend.uk-legend.flex-center.page-title
-#   = @regular_band.name
-# .uk-container.flex-center.band-show-container
-#   .uk-card.uk-card-large.show-band
-#     .uk-card-media-top
-#       %img.show-band-picture{"src" => "http://www.acappellazone.com/fileadmin/user_upload/ACAPPELLAZONE/TOP_ACTS/Slixs/SLIXS-hagen-wolf-3_slider.jpg"}
-#     .uk-card-body
-#       .uk-container
-#         .show-band-description
-#           .show-band-label
-#             バンドの説明
-#           .show-band-body
-#             Pentatonix (abbreviated PTX) is an American a cappella group from Arlington, Texas, consisting of vocalists Scott Hoying, Mitch Grassi, Kirstin Maldonado, Kevin Olusola, and Matt Sallee. Avi Kaplan was formerly a member of the group; he was replaced by Sallee in 2017
-#         .show-band-members
-#           .show-band-label
-#             バンドメンバー
-#           .show-band-body
-#             %ul.uk-list.show-band-members-ul
-#               -@regular_band.band_members.includes(:user).each do |member|
-#                 %li.show-band-members-list
-#                   .show-band-members-list-name.uk-float-left
-#                     = member.user.name
-#                   .show-band-members-list-mic-number.uk-float-right
-#                     マイク番号：
-#                     = member.mic_number
-#         .show-band-master
-#           .show-band-label
-#             バンマス
-#           .show-band-body
-#             = @regular_band.master.name
-#         .show-band-pa
-#           .show-band-label
-#             PA
-#           .show-band-body
-#             = @regular_band.pa.name

app/views/regular_bands/untitled.html.erb
<div class="uk-section uk-section-muted uk-preserve-color uk-section-xsmall">
                  <div class="uk-container">
                    <input name='regular_band[master_id]' type='hidden' value='${id}'>
                    <div class="band-member_year-section">
                      ${year} ${section}
                    </div>
                    <div class="band-member_name">
                      ${name}
                    </div>
                    <a class="band-member_remove-button">消去</a>
                  </div>
                </div>


<div class="uk-section uk-section-muted uk-preserve-color uk-section-xsmall">
                  <div class="uk-container">
                    <input name='regular_band[pa_id]' type='hidden' value='${id}'>
                    <div class="band-member_year-section">
                      ${year} ${section}
                    </div>
                    <div class="band-member_name">
                      ${name}
                    </div>
                    <a class="band-member_remove-button">消去</a>
                  </div>
                </div>

app/views/regular_bands/untitled.html.haml
.uk-section.uk-section-muted.uk-preserve-color.uk-section-xsmall
  .uk-container
    %input{:name => "regular_band[master_id]", :type => "hidden", :value => "${id}"}/
    .band-member_year-section
      ${year} ${section}
    .band-member_name
      ${name}
    %a.band-member_remove-button 消去

.uk-section.uk-section-muted.uk-preserve-color.uk-section-xsmall
  .uk-container
    %input{:name => "regular_band[pa_id]", :type => "hidden", :value => "${id}"}/
    .band-member_year-section
      ${year} ${section}
    .band-member_name
      ${name}
    %a.band-member_remove-button 消去