config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  ActiveAdmin.routes(self)
  root to: "users#show"
  devise_for :users
  resources :users, only: [:show] do
    collection do
      get "search"
    end
  end
  resources :event_entries
  resources :reviews
  resources :comments
  resources :presentations
  resources :events
  resources :room_usages, only: %i[index new]
  resources :mics
  resources :bands, only: [:index]
  resources :regular_bands, only: %i[new create show edit update]
  resources :temporal_bands, only: %i[new create show edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/mics/order/:id", to: "mics#order"
  post "/mics/order/:id/:order", to: "mics#order_update"
end

app/models/band/temporal_band.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bands
#
#  id            :bigint(8)        not null, primary key
#  description   :text
#  name          :string           not null
#  registeration :boolean          not null
#  type          :string
#  web_url       :string
#  year          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  master_id     :bigint(8)        not null
#  pa_id         :bigint(8)        not null
#
# Indexes
#
#  index_bands_on_master_id  (master_id)
#  index_bands_on_pa_id      (pa_id)
#
# Foreign Keys
#
#  fk_rails_...  (master_id => users.id)
#  fk_rails_...  (pa_id => users.id)
#

class TemporalBandValidator < ActiveModel::Validator
  def validate(record)
    unless !record.type.nil? && record.type.match("TemporalBand")
      record.errors[:type] << "は企画バンドでなければいけません"
    end
  end
end

class TemporalBand < Band
  belongs_to :pa, class_name: "User", foreign_key: "pa_id", optional: true
  validates_with TemporalBandValidator
end

app/controllers/temporal_bands_controller.rb
# frozen_string_literal: true

class TemporalBandsController < ApplicationController
  before_action :set_temporal_band, only: %i[edit update show]

  def new
    @temporal_band = RegularBand.new
  end

  def create
    @temporal_band = new_temporal_band(temporal_band_params)
    if @temporal_band.save
      @temporal_band_members = new_members(temporal_band_params, @temporal_band)
      success = @temporal_band_members.map(&:save)
      if success.all?
        redirect_to root_path, notice: "バンドを作成しました"
      else
        @temporal_band_members.map(&:delete)
        render :new, notice: "バンドメンバーを登録できませんでした"
      end
    else
      render :new, notice: "バンドメンバーを登録できませんでした"
    end
  end

  def show; end

  def edit; end

  def update; end

  private

  def temporal_band_params
    params.require(:temporal_band).permit(
      :name,
      :description
    ).merge(params.require(:band).permit(
              :master_id,
              members: %i[
                user_id
                mic_number
              ]
            ))
  end

  def new_temporal_band(params)
    band = RegularBand.new(
      type: "TemporalBand",
      name: params[:name],
      description: params[:description],
      master_id: params[:master_id]
    )
    band
  end

  def new_members(params, band)
    band_members = []
    if params[:members].present?
      params[:members].map do |member|
        raise "error" if member[:user_id].nil?
        raise "error" if member[:mic_number].nil?

        band_member = BandMember.new(
          user_id: member[:user_id],
          band_id: band.id,
          mic_number: member[:mic_number]
        )
        band_members.push(band_member)
      end
    end
    band_members
  end

  def set_temporal_band
    @temporal_band = RegularBand.find(params[:id])
  end
end

app/helpers/temporal_bands_helper.rb
# frozen_string_literal: true

module TemporalBandsHelper
end

app/views/temporal_bands/edit.html.haml
.flex-center
  = form_for @temporal_band do |f|
    - if @temporal_band.errors.any?
      #error_explanation
        %h2= "#{@temporal_band.errors.full_messages.count}件のエラーが発生たため、バンドは編集されませんでした："
        %ul
          - @temporal_band.errors.full_messages.each do |message|
            %li= message
    =f.hidden_field :type, value: "TemporalBand"
    %legend.uk-legend.form-title.flex-center 企画バンド編集
    .field
      = f.label :企画名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :企画責任者, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-xsmall
          .uk-container
            %input{:name => "temporal_band[master_id]", :type => "hidden", :value => "#{@temporal_band.master.id}"}
            .band-member_year-section
              = @temporal_band.master.year
              = @temporal_band.master.section.name
            .band-member_name
              = @temporal_band.master.name
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
              -@temporal_band.users.includes(:section).each do |user|
                %li.band-member
                  %input{:name => "temporal_band[members][][user_id]", :type => "hidden", :value => "#{user.id}"}
                  .band-member_year-section
                    = user.year
                    = user.section.name
                  .band-member_name
                    = user.name
                  .band-member_mic-number
                    マイク番号
                    %select{:name => "temporal_band[members][][mic_number]"}
                      %option{:value => "1"} 1番
                      %option{:value => "2"} 2番
                      %option{:value => "3"} 3番
                      %option{:value => "4"} 4番
                      %option{:value => "5"} 5番
                      %option{:value => "6"} 6番
                      %option{:value => "7"} 7番
                  %a.band-member_remove-button 消去
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"

app/views/temporal_bands/new.html.haml
.flex-center
  = form_for @temporal_band do |f|
    - if @temporal_band.errors.any?
      #error_explanation
        %h2= "#{@temporal_band.errors.full_messages.count}件のエラーが発生たため、バンドは登録されませんでした："
        %ul
          - @temporal_band.errors.full_messages.each do |message|
            %li= message
    %legend.uk-legend.form-title.flex-center 企画バンド登録
    .field
      = f.label :企画名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :企画責任者, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"

app/views/temporal_bands/show.html.haml
- if user_band_member?(@temporal_band, current_user)
  = link_to "編集", edit_temporal_band_path, class: "show-band-edit"
%legend.uk-legend.flex-center.page-title
  = @temporal_band.name
.uk-container.flex-center.band-show-container
  .uk-card.uk-card-large.uk-card-body.show-band
      .uk-container
        .show-band-members
          .show-band-label
            企画メンバー
          .show-band-body
            %ul.uk-list.show-band-members-ul
              -@temporal_band.band_members.includes(:user).each do |member|
                %li.show-band-members-list
                  .show-band-members-list-name.uk-float-left
                    = member.user.name
                  .show-band-members-list-mic-number.uk-float-right
                    マイク番号：
                    = member.mic_number
        .show-band-master
          .show-band-label
            企画責任者
          .show-band-body
            = @temporal_band.master.name