config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  ActiveAdmin.routes(self)
  root to: "users#show"
  devise_for :users
  resources :users, only: [:show] do
    collection do
      get "search"
    end
  end
  resources :event_entries
  resources :reviews
  resources :comments
  resources :presentations
  resources :events
  resources :room_usages, only: %i[index new]
  resources :mics
  resources :bands, only: [:index]
  resources :regular_bands, only: %i[new create show edit update]
  resources :temporal_bands, only: %i[new create show edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/mics/order/:id", to: "mics#order"
  post "/mics/order/:id/:order", to: "mics#order_update"
end

app/models/band/band.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bands
#
#  id            :bigint(8)        not null, primary key
#  description   :text
#  name          :string           not null
#  registeration :boolean          not null
#  type          :string
#  web_url       :string
#  year          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  master_id     :bigint(8)        not null
#  pa_id         :bigint(8)        not null
#
# Indexes
#
#  index_bands_on_master_id  (master_id)
#  index_bands_on_pa_id      (pa_id)
#
# Foreign Keys
#
#  fk_rails_...  (master_id => users.id)
#  fk_rails_...  (pa_id => users.id)
#

class Band < ApplicationRecord
  has_many :mics, dependent: :destroy
  has_many :band_members
  has_many :users, through: :band_members
  has_many :room_usages
  belongs_to :master, class_name: "User", foreign_key: "master_id"
  validates :name, presence: true
  validates :type, presence: true
end

app/models/band/regular_band.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bands
#
#  id            :bigint(8)        not null, primary key
#  description   :text
#  name          :string           not null
#  registeration :boolean          not null
#  type          :string
#  web_url       :string
#  year          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  master_id     :bigint(8)        not null
#  pa_id         :bigint(8)        not null
#
# Indexes
#
#  index_bands_on_master_id  (master_id)
#  index_bands_on_pa_id      (pa_id)
#
# Foreign Keys
#
#  fk_rails_...  (master_id => users.id)
#  fk_rails_...  (pa_id => users.id)
#

class RegularBandValidator < ActiveModel::Validator
  def validate(record)
    unless !record.type.nil? && record.type.match("RegularBand")
      record.errors[:type] << "は正規バンドでなければいけません"
    end
  end
end

class RegularBand < Band
  include ActiveModel::Validations
  belongs_to :pa, class_name: "User", foreign_key: "pa_id"
  validates :year, presence: true
  validates :description, presence: true
  validates_with RegularBandValidator
end

app/models/band/temporal_band.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bands
#
#  id            :bigint(8)        not null, primary key
#  description   :text
#  name          :string           not null
#  registeration :boolean          not null
#  type          :string
#  web_url       :string
#  year          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  master_id     :bigint(8)        not null
#  pa_id         :bigint(8)        not null
#
# Indexes
#
#  index_bands_on_master_id  (master_id)
#  index_bands_on_pa_id      (pa_id)
#
# Foreign Keys
#
#  fk_rails_...  (master_id => users.id)
#  fk_rails_...  (pa_id => users.id)
#

class TemporalBandValidator < ActiveModel::Validator
  def validate(record)
    unless !record.type.nil? && record.type.match("TemporalBand")
      record.errors[:type] << "は企画バンドでなければいけません"
    end
  end
end

class TemporalBand < Band
  belongs_to :pa, class_name: "User", foreign_key: "pa_id", optional: true
  validates_with TemporalBandValidator
end

app/controllers/bands_controller.rb
# frozen_string_literal: true

# きょうすけ担当
class BandsController < ApplicationController
  # バンド一覧画面
  def index
    @regular_bands = RegularBand.includes(:users).all.decorate
    @temporal_bands = TemporalBand.includes(:users).all.decorate
  end

  def destroy; end
end

app/helpers/bands_helper.rb
# frozen_string_literal: true

module BandsHelper
  def user_band_member?(band, user)
    band.users.each do |member|
      return true if user == member
    end
    false
  end
end

app/views/bands/index.html.haml
.uk-container.band-index-container
  %legend.uk-legend.flex-center.page-title バンド一覧

  %div{"uk-filter" => "target: .js-filter"}
    .uk-grid-small.uk-grid-divider.uk-child-width-auto#pc-band-navigator{"uk-grid" => ""}
      %div
        %ul.uk-subnav.uk-subnav-pill
          %li.uk-active.all-band-button-pc{"uk-filter-control" => ""}
            %a All
      %div
        %ul.uk-subnav.uk-subnav-pill
          %li.regular-button-pc{"uk-filter-control" => "filter: [data-band-type='regular']; group: data-band-type"}
            %a 正規バンド
          %li.temporal-button-pc{"uk-filter-control" => "filter: [data-band-type='temporal']; group: data-band-type"}
            %a 企画バンド
      %div
        %ul.uk-subnav.uk-subnav-pill
          %li.mix-3-button-pc{"uk-filter-control" => "filter: [data-band-formation='mix-3']; group: data-band-formation"}
            %a 混声3人
          %li.mix-4-button-pc{"uk-filter-control" => "filter: [data-band-formation='mix-4']; group: data-band-formation"}
            %a 混声4人
          %li.mix-5-button-pc{"uk-filter-control" => "filter: [data-band-formation='mix-5']; group: data-band-formation"}
            %a 混声5人
          %li.mix-6-button-pc{"uk-filter-control" => "filter: [data-band-formation='mix-6']; group: data-band-formation"}
            %a 混声6人
          %li.mix-7-button-pc{"uk-filter-control" => "filter: [data-band-formation='mix-7']; group: data-band-formation"}
            %a 混声7人
          %li.boys-band-button-pc{"uk-filter-control" => "filter: [data-band-formation='boys-band']; group: data-band-formation"}
            %a ヤロバン
          %li.girls-band-button-pc{"uk-filter-control" => "filter: [data-band-formation='girls-band']; group: data-band-formation"}
            %a ギャルバン



    %ul.js-filter.uk-child-width-1-2.uk-child-width-1-3@m{'uk-grid': "", 'uk-height-match': ''}
      -@regular_bands.each do |regular_band|
        %li{"data-band-type" => "regular", "data-band-formation" => "#{regular_band.band_formation}"}
          = link_to regular_band_path(regular_band) do
            .uk-card.uk-card-default.uk-height-1-1{class: "#{regular_band.band_formation}"}
              .uk-card-media-top
                %img.uk-width-1-1{"src" => "http://www.acappellazone.com/fileadmin/user_upload/ACAPPELLAZONE/TOP_ACTS/Slixs/SLIXS-hagen-wolf-3_slider.jpg"}
              .uk-card-body.uk-padding-small
                %h3= regular_band.name
                .uk-text-meta{style: 'font-size:0.7em'}= regular_band.description
      -@temporal_bands.each do |temporal_band|
        %li{"data-band-type" => "temporal", "data-band-formation" => "#{temporal_band.band_formation}"}
          = link_to temporal_band_path(temporal_band) do
            .uk-card.uk-card-default.uk-height-1-1{class: "#{temporal_band.band_formation}"}
              .uk-card-media-top
                %img.uk-width-1-1{"src" => "http://www.acappellazone.com/fileadmin/user_upload/ACAPPELLAZONE/TOP_ACTS/Slixs/SLIXS-hagen-wolf-3_slider.jpg"}
              .uk-card-body.uk-padding-small
                %h3= temporal_band.name
                .uk-text-meta.uk-text-truncate{style: 'font-size:0.7em;height:100px'}= temporal_band.event.name



      -# %li{"data-band-type" => "regular", "data-band-formation" => "mix-5"}
      -#   .uk-card.uk-card-default.uk-card-body.index-band.uk-padding-small.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Pentatonix
      -#       %img.index-band-picture.uk-overflow-hidden.uk-height-1-3{"src" => "https://www.billboard.com/files/styles/article_main_image/public/media/Pentatonix-press-photo-cr-Vijat-Mohindra-2017-billboard-1548.jpg"}
      -#       %h3.index-band-description Pentatonix (abbreviated PTX) is an American a cappella group from Arlington, Texas, consisting of vocalists Scott Hoying, Mitch Grassi, Kirstin Maldonado, Kevin Olusola, and Matt Sallee. Avi Kaplan was formerly a member of the group; he was replaced by Sallee in 2017
      -# %li{"data-band-type" => "regular", "data-band-formation" => "boys-band"}
      -#   .uk-card.uk-card-primary.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Take 6
      -#       %img.index-band-picture{"src" => "https://assets.jazziz.com/uploads/2016/03/Take6-768x512.jpg"}
      -#       %h3.index-band-description Take 6 is an American a cappella gospel sextet formed in 1980 on the campus of Oakwood College in Huntsville, Alabama.[1] The group integrates jazz with spiritual and inspirational lyrics.
      -# %li{"data-band-type" => "regular", "data-band-formation" => "mix-5"}
      -#   .uk-card.uk-card-default.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name The Real Group
      -#       %img.index-band-picture{"src" => "https://images.sk-static.com/images/media/profile_images/artists/534223/huge_avatar"}
      -#       %h3.index-band-description The Real Group has performed more than 2000 concerts worldwide.[3] In 2002 The Real Group performed at the opening ceremony of the FIFA World Cup in Seoul, South Korea to an audience of 60,000. On 22 December 1993, to commemorate the fiftieth birthday of
      -# %li{"data-band-type" => "regular", "data-band-formation" => "mix-5"}
      -#   .uk-card.uk-card-default.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Vox One
      -#       %img.index-band-picture.uk-overflow-hidden.uk-height-1-3{"src" => "https://images-na.ssl-images-amazon.com/images/I/51o0hT6RmWL._SY355_.jpg"}
      -#       %h3.index-band-description 1988年、当時バークリー音楽院に在籍していた松岡由美子が学内で知り合った仲間とともにVOX ONEを結成。幾度かのメンバーチェンジを得て1993年にアルバム『VOX ONE』でデビュー。その後アメリカで3枚、日本で2枚のアルバムを発表、米国アカペラ連盟(CASA)主催のアカペラレコード大賞(CARA)でアルバム大賞を受賞するなど活躍をしたが1997年活動停止。


      -# %li{"data-band-type" => "regular", "data-band-formation" => "girls-band"}
      -#   .uk-card.uk-card-secondary.uk-card-body.index-band.girls-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Little Glee Monster
      -#       %img.index-band-picture{"src" => "https://cdn.fashionsnap.com/article/assets_c/2018/08/lgm20180831-001-thumb-750xauto-921712.jpg"}
      -#       %h3.index-band-description リトル グリー モンスター）は、日本のガールズボーカル音楽グループ。2013年結成。2014年に6人組ボーカルグループとしてメジャーデビュー。現在は5人で活動している。略称はリトグリ。所属事務所はワタナベエンターテインメント。レーベルはソニー・ミュージックレコーズ。
      -# %li{"data-band-type" => "regular", "data-band-formation" => "girls-band"}
      -#   .uk-card.uk-card-secondary.uk-card-body.index-band.girls-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Little Glee Monster
      -#       %img.index-band-picture{"src" => "https://cdn.fashionsnap.com/article/assets_c/2018/08/lgm20180831-001-thumb-750xauto-921712.jpg"}
      -#       %h3.index-band-description リトル グリー モンスター）は、日本のガールズボーカル音楽グループ。2013年結成。2014年に6人組ボーカルグループとしてメジャーデビュー。現在は5人で活動している。略称はリトグリ。所属事務所はワタナベエンターテインメント。レーベルはソニー・ミュージックレコーズ。
      -# %li{"data-band-type" => "regular", "data-band-formation" => "boys-band"}
      -#   .uk-card.uk-card-primary.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Take 6
      -#       %img.index-band-picture{"src" => "https://assets.jazziz.com/uploads/2016/03/Take6-768x512.jpg"}
      -#       %h3.index-band-description Take 6 is an American a cappella gospel sextet formed in 1980 on the campus of Oakwood College in Huntsville, Alabama.[1] The group integrates jazz with spiritual and inspirational lyrics.
      -# %li{"data-band-type" => "regular", "data-band-formation" => "girls-band"}
      -#   .uk-card.uk-card-secondary.uk-card-body.index-band.girls-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Little Glee Monster
      -#       %img.index-band-picture{"src" => "https://cdn.fashionsnap.com/article/assets_c/2018/08/lgm20180831-001-thumb-750xauto-921712.jpg"}
      -#       %h3.index-band-description リトル グリー モンスター）は、日本のガールズボーカル音楽グループ。2013年結成。2014年に6人組ボーカルグループとしてメジャーデビュー。現在は5人で活動している。略称はリトグリ。所属事務所はワタナベエンターテインメント。レーベルはソニー・ミュージックレコーズ。
      -# %li{"data-band-type" => "regular", "data-band-formation" => "boys-band"}
      -#   .uk-card.uk-card-primary.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name The Gospellers
      -#       %img.index-band-picture{"src" => "http://sp.gospellers.tv/image/gospellers/bnr/mainimage_gospellers-1_116.jpg"}
      -#       %h3.index-band-description 1989年に、國學院大學久我山高等学校で同じクラスだった村上てつやと黒沢薫が他の同級生と共にコーラスグループを結成し、高校の文化祭で歌を披露する。1991年、村上が早稲田大学に入学し、アカペラサークル"Street Corner Symphony”の門を叩く。そして、当時國學院大學に通っていた黒沢を同サークルに誘い、村上、黒沢と他4名で初代ゴスペラーズが結成される（初代は6人）。初代リーダー脱退後、インディーズとして当時のメンバーで録音された「Down To Street」を発売。これが唯一2代目ゴスペラーズの音源となった。
      -# %li{"data-band-type" => "regular", "data-band-formation" => "mix-5"}
      -#   .uk-card.uk-card-default.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Pentatonix
      -#       %img.index-band-picture{"src" => "https://www.billboard.com/files/styles/article_main_image/public/media/Pentatonix-press-photo-cr-Vijat-Mohindra-2017-billboard-1548.jpg"}
      -#       %h3.index-band-description Pentatonix (abbreviated PTX) is an American a cappella group from Arlington, Texas, consisting of vocalists Scott Hoying, Mitch Grassi, Kirstin Maldonado, Kevin Olusola, and Matt Sallee. Avi Kaplan was formerly a member of the group; he was replaced by Sallee in 2017
      -# %li{"data-band-type" => "regular", "data-band-formation" => "boys-band"}
      -#   .uk-card.uk-card-primary.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Take 6
      -#       %img.index-band-picture{"src" => "https://assets.jazziz.com/uploads/2016/03/Take6-768x512.jpg"}
      -#       %h3.index-band-description Take 6 is an American a cappella gospel sextet formed in 1980 on the campus of Oakwood College in Huntsville, Alabama.[1] The group integrates jazz with spiritual and inspirational lyrics.
      -# %li{"data-band-type" => "regular", "data-band-formation" => "girls-band"}
      -#   .uk-card.uk-card-secondary.uk-card-body.index-band.girls-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Little Glee Monster
      -#       %img.index-band-picture{"src" => "https://cdn.fashionsnap.com/article/assets_c/2018/08/lgm20180831-001-thumb-750xauto-921712.jpg"}
      -#       %h3.index-band-description リトル グリー モンスター）は、日本のガールズボーカル音楽グループ。2013年結成。2014年に6人組ボーカルグループとしてメジャーデビュー。現在は5人で活動している。略称はリトグリ。所属事務所はワタナベエンターテインメント。レーベルはソニー・ミュージックレコーズ。

      -# %li{"data-band-type" => "temporal", "data-band-formation" => "mix-5"}
      -#   .uk-card.uk-card-default.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name こまだダンススタジオ
      -# %li{"data-band-type" => "temporal", "data-band-formation" => "girls-band"}
      -#   .uk-card.uk-card-body.index-band.girls-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name ギャルバンゴス
      -# %li{"data-band-type" => "temporal", "data-band-formation" => "boys-band"}
      -#   .uk-card.uk-card-primary.uk-card-body.index-band.uk-height-1-1
      -#     .uk-container
      -#       %h3.index-band-name Committed企画
  %a.mobile-band-navigator-button{:href => "#offcanvas-slide", "uk-toggle" => ""}
    %span.uk-form-icon.uk-form-icon-flip.band-search-icon{"uk-icon" => "icon: search"}
  #offcanvas-slide.mobile-band-navigator{"uk-offcanvas" => ""}
    .uk-offcanvas-bar
      %ul.uk-nav.uk-nav-default
        %li.uk-active.all-band-button-mobile
          %a All
        %li.uk-nav-divider
        %li.uk-nav-header バンドの種類
        %ul.uk-nav-sub
          %li.regular-button-mobile
            %a 正規バンド
          %li.temporal-button-mobile
            %a 企画バンド
        %li.uk-nav-divider
        %li.uk-nav-header バンドの構成
        %ul.uk-nav-sub
          %li.mix-3-button-mobile
            %a 混声3人
          %li.mix-4-button-mobile
            %a 混声4人
          %li.mix-5-button-mobile
            %a 混声5人
          %li.mix-6-button-mobile
            %a 混声6人
          %li.mix-7-button-mobile
            %a 混声7人
          %li.boys-band-button-mobile
            %a ヤロバン
          %li.girls-band-button-mobile
            %a ギャルバン

app/views/bands/new_regular.html.haml
.flex-center
  = form_for @band do |f|
    - if @band.errors.any?
      #error_explanation
        %h2= "#{@band.errors.full_messages.count}件のエラーが発生たため、バンドは登録されませんでした："
        %ul
          - @band.errors.full_messages.each do |message|
            %li= message
    =f.hidden_field :type, value: "RegularBand"
    %legend.uk-legend.form-title.flex-center 正規バンド登録
    .field
      = f.label :バンド名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :band_name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :結成年, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: calendar"}
        = f.text_field :band_year, class: "uk-input field-input"
    .field
      = f.label :バンドの説明, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: pencil"}
        = f.text_field :description, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :Webページ, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: world"}
        = f.text_field :web_url, autocomplete: "off", class: "uk-input field-input"
    .field
      = f.label :バンドマスター, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
    .field
      = f.label :PA, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#pa-search-field{placeholder: "PAの名前を入力してください", type: "text", name: "keyword"}
        #pa-search-result
      #pa-box
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"

app/views/bands/new_temporal.html.haml
.flex-center
  = form_for @band do |f|
    - if @band.errors.any?
      #error_explanation
        %h2= "#{@band.errors.full_messages.count}件のエラーが発生たため、バンドは登録されませんでした："
        %ul
          - @band.errors.full_messages.each do |message|
            %li= message
    =f.hidden_field :type, value: "TemporalBand"
    %legend.uk-legend.form-title.flex-center 企画バンド登録
    .field
      = f.label :バンド名, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: tag"}
        = f.text_field :band_name, autofocus: true, class: "uk-input field-input"
    .field
      = f.label :企画責任者, class: "field-label"
      .uk-inline
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: user"}
        %input.uk-input.field-input#master-search-field{placeholder: "バンマス名を入力してください", type: "text", name: "keyword"}
        #master-search-result
      #master-box
    .field
      %label.field-label メンバーを追加
      .uk-inline.uk-position-relative
        %span.uk-form-icon.uk-form-icon-flip{"uk-icon" => "icon: search"}
        %input.uk-input.field-input#member-search-field{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword"}
        #member-search-result
    .field
      %label.field-label バンドメンバー
      .uk-inline
        .uk-section.uk-section-muted.uk-preserve-color.uk-section-small
          .uk-container
            %ul.uk-list.band-member-list
    .actions.flex-center
      = f.submit "登録", class: "uk-button uk-button-primary form-button"